"""role added

Revision ID: 5125809a0eea
Revises: 8a016f05bf82
Create Date: 2025-05-04 21:57:02.050127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5125809a0eea"
down_revision: Union[str, None] = "8a016f05bf82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", sa.Enum("accountant", "user", name="roles"), nullable=False),
    )
    op.drop_column("users", "roles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("roles", mysql.ENUM("accountant", "user"), nullable=True)
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
