"""role added

Revision ID: 8a016f05bf82
Revises: cb40f1bbb354
Create Date: 2025-05-04 21:54:16.796795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8a016f05bf82"
down_revision: Union[str, None] = "cb40f1bbb354"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "roles", existing_type=mysql.ENUM("accountant", "user"), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "roles", existing_type=mysql.ENUM("accountant", "user"), nullable=False
    )
    # ### end Alembic commands ###
